overwrite: true
schema: "http://localhost:3000/graphql"
documents: "src/queries/**/*.ts"
generates:
  src/generated/graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
    config:
      withHooks: true
      preResolveTypes: true
      avoidOptionals: true
      typesPrefix: I
